// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/app/components/layout/Header";
// import Footer from "./components/layout/Footer";
// import ScrollToTop from "@/app/components/ScrollToTop"; // Adjust path if needed

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Header />
//         {children}
//         <ScrollToTop /> {/* Add this */}
//         <Footer />
//       </body>
//     </html>
//   );
// }



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/app/components/layout/Header"; // Adjust if path differs
// import Footer from "./components/layout/Footer"; // Adjust if path differs
// import ScrollToTop from "@/app/components/ScrollToTop";
// import LoadingProvider from "@/app/providers/LoadingProvider"; // No change needed here

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Header />
//         <LoadingProvider>
//           {children}
//           <ScrollToTop />
//         </LoadingProvider>
//         <Footer />
//       </body>
//     </html>
//   );
// }





import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layout/Header";
import Footer from "./components/layout/Footer";
import ScrollToTop from "@/app/components/ScrollToTop";
import LoadingProvider from "@/app/providers/LoadingProvider";
import DpWebzCursor from "@/app/components/DpWebzCursor"; // Updated import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <LoadingProvider>
          {children}
          <ScrollToTop />
        </LoadingProvider>
        <Footer />
        <DpWebzCursor /> {/* Updated usage */}
      </body>
    </html>
  );
}
